apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: f1-dashboard
  namespace: user-mascret
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: f1-dashboard.user.lab.sspcloud.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: f1-dashboard
                port:
                  number: 80
  tls:
    - hosts:
        - f1-dashboard.user.lab.sspcloud.fr
